### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '?' in phar:///usr/sbin/wp/php/WP_CLI/Runner.php

### ISSUE THREAD

**Issue by amys94fr** [wp-cli/search-replace-command#71]
Hi wp-cli Team,
I got this error when I use search-replace command 
wp --allow-root search-replace 'http://mywebsite.com' 'https://mywebsite.com' --recurse-objects

PHP Parse error:  syntax error, unexpected '?' in phar:///usr/sbin/wp/php/WP_CLI/Runner.php(1138) : eval()'d code on line 1

**Comment by gitlost** [comment]
This probably means the initial `<?php` isn't getting stripped from your `wp-config.php` due to initial non-visible characters, probably a [Unicode `BOM`](https://en.wikipedia.org/wiki/Byte_order_mark). As mentioned in https://github.com/wp-cli/wp-cli/issues/4661#issuecomment-362853617 could you do
```
hexdump -C wp-config.php | head -1
```
and if you see
```
ef bb bf 3c 3f 70 68 70  0a 2f 2a 2a 0a 20 2a 20  |...<?php./**. * |
```
then remove the `BOM` (`ef bb bf`) from your `wp-config.php` using your favourite (hex) editor.

(This situation will be dealt with by WP-CLI in a future release.)

**Comment by amys94fr** [comment]
Thanks you 
I run this command to remove the BOM and now it works 
`sed -i '1s/^\xEF\xBB\xBF//' wp-config.php`

**Comment by gitlost** [comment]
Thanks for the feedback @amys94fr . Using `sed` is a nice solution. This issue should be added the https://make.wordpress.org/cli/handbook/common-issues/ I think, so will use it there.

**Comment by h3nr1ke** [comment]
Thanks, it solved the problem here... =)
used this to check
`hexdump -C wp-config.php | head -1`

floowed by

`sed -i '1s/^\xEF\xBB\xBF//' wp-config.php`

to correct the file...

**Comment by student9er** [comment]
Greetings I am having a similar issue...
PHP Parse error:  syntax error, unexpected '*', expecting end of file in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code on line 88
